メニューCSS
jawordpressorg/wordcamp-japan-theme pull request #4
Opened 2017-11-07 14:37 UTC by chiilog

メニュー用CSS作成しました。
（後々scssファイル分割します。とりあえずお試し・・・）

2017-11-10 16:52 UTC, miya0001 commented
Before/Afterのスクショとか添付してくれると判断しやすいかもですね。
「ソース読め」だと単純に判断すること自体がめんどくさいと思われちゃって、結果的に放置されます。^^

2017-11-11 07:21 UTC, chiilog commented
@miya0001 なるほど・・！ありがとうございます！！スクショ撮ってつけますー！

2017-11-11 08:21 UTC, chiilog commented
## before
### PC
![2017-11-11 17 18 50](https://user-images.githubusercontent.com/25993565/32687649-8c08393c-c704-11e7-8f8b-c78dfec12d51.png)
 
### SP
![2017-11-11 17 19 04](https://user-images.githubusercontent.com/25993565/32687652-9855d2b2-c704-11e7-97f7-0c602927e216.png)

## after
### PC
![2017-11-11 17 16 44](https://user-images.githubusercontent.com/25993565/32687654-a090fdda-c704-11e7-8dab-f260e4ae202e.png)

### SP
![2017-11-11 17 17 07](https://user-images.githubusercontent.com/25993565/32687656-a8f9ef72-c704-11e7-868a-0c1c9c5dfa55.png)

2017-11-11 08:29 UTC, torounit requested changes
Do not remove .node-version.

2017-11-12 09:44 UTC, torounit approved these changes

2017-11-12 09:44 UTC, torounit requested changes
package-lock.json とかも消さないで・・・・

2017-11-12 13:54 UTC, chiilog commented
足しました・・・スイマセン

2017-11-12 20:57 UTC, torounit approved these changes

2017-11-12 20:58 UTC, merged